### ISSUE TITLE
Search results don't render markdown

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/pse.dev#362]
Loving the new search feature!!! (#75)

Noticed that the results don't properly render markdown (showing the syntax in plaintext), e.g.

<img width="756" alt="Image" src="https://github.com/user-attachments/assets/3f1445f2-21e2-4808-ac4a-425e7609d1b8" />

<img width="755" alt="Image" src="https://github.com/user-attachments/assets/b5abda34-c1d0-47d6-94b1-2b5cdd8afe31" />

**Comment by kalidiagne** [comment]
solved here https://github.com/privacy-scaling-explorations/pse.dev/pull/363

**Comment by samajammin** [comment]
Thanks @kalidiagne ! Still seeing some issues though:

<img width="752" alt="Image" src="https://github.com/user-attachments/assets/917b1e67-9db0-4b51-b30f-4d9ff5bce2d6" />

**Comment by samajammin** [comment]
Perhaps it's in cases where the link is cut off from the preview text being truncated?

**Comment by kalidiagne** [comment]
@samajammin updated to show everything as text also

**Comment by kalidiagne** [comment]
Will close for know! feel free to open if there is any othe rissue that needs to be addressed

**Comment by samajammin** [comment]
Noticed this again (square brackets of markdown links displaying):
<img width="793" alt="Image" src="https://github.com/user-attachments/assets/2a532036-dfe1-4ca7-a44f-788ab957150d" />
